name = "accusation-v2"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "accusation-card-tooldb"
database_id = "940c8db3-67fb-4321-84bd-3be478a70b38"
migrations_dir = "migrations"
