/**
 * src/data/qaData.js 的格式契約：寫入與解析放在同一處，避免格式異動時
 * 讀取端靜默失效（sync-qa 會每週重寫檔案、安全檢查會直接拋錯）。
 */

const QA_EXPORT_PATTERN = /export const qaData = ([\s\S]*);\s*$/;

/** @param {unknown[]} data */
export function formatQaModule(data) {
  return `// Auto-generated by scripts/sync-qa.mjs — do not edit
// 最後同步：${new Date().toLocaleString('zh-TW', { timeZone: 'Asia/Taipei' })}

export const qaData = ${JSON.stringify(data, null, 2)};\n`;
}

/**
 * @param {string} source qaData.js 的完整內容
 * @returns {unknown[] | null} 格式不符時回傳 null
 */
export function parseQaModule(source) {
  const match = source.match(QA_EXPORT_PATTERN);
  if (!match) return null;
  try {
    return JSON.parse(match[1]);
  } catch {
    return null;
  }
}
