import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const SHEETS = [
  { label: '通用規則', url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSPgmF_9uiGkG5t_1GxEnEBD3GSVFvj1MYTaXtKjLjIEa_XqIQcwrWpY9DHELim8zOhVkKcKCxIpSh8/pub?gid=1169306065&single=true&output=csv' },
  { label: '白狐神社', url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSPgmF_9uiGkG5t_1GxEnEBD3GSVFvj1MYTaXtKjLjIEa_XqIQcwrWpY9DHELim8zOhVkKcKCxIpSh8/pub?gid=1973167497&single=true&output=csv' },
  { label: '鴉教團', url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSPgmF_9uiGkG5t_1GxEnEBD3GSVFvj1MYTaXtKjLjIEa_XqIQcwrWpY9DHELim8zOhVkKcKCxIpSh8/pub?gid=1253175233&single=true&output=csv' },
  { label: '瘋人院', url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSPgmF_9uiGkG5t_1GxEnEBD3GSVFvj1MYTaXtKjLjIEa_XqIQcwrWpY9DHELim8zOhVkKcKCxIpSh8/pub?gid=332236121&single=true&output=csv' },
  { label: '門教團', url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSPgmF_9uiGkG5t_1GxEnEBD3GSVFvj1MYTaXtKjLjIEa_XqIQcwrWpY9DHELim8zOhVkKcKCxIpSh8/pub?gid=2076037145&single=true&output=csv' },
  { label: '逐光者', url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSPgmF_9uiGkG5t_1GxEnEBD3GSVFvj1MYTaXtKjLjIEa_XqIQcwrWpY9DHELim8zOhVkKcKCxIpSh8/pub?gid=719906907&single=true&output=csv' },
  { label: '禁忌廚房', url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSPgmF_9uiGkG5t_1GxEnEBD3GSVFvj1MYTaXtKjLjIEa_XqIQcwrWpY9DHELim8zOhVkKcKCxIpSh8/pub?gid=1316542157&single=true&output=csv' },
  { label: '放逐者', url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSPgmF_9uiGkG5t_1GxEnEBD3GSVFvj1MYTaXtKjLjIEa_XqIQcwrWpY9DHELim8zOhVkKcKCxIpSh8/pub?gid=333010439&single=true&output=csv' },
];

const OUTPUT_PATH = resolve(__dirname, '../src/data/qaData.js');
const PLACEHOLDER = { q: '目前尚無特定 QA', a: '歡迎補充！' };

async function fetchCSV(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}`);
  return res.text();
}

function parseCSV(text) {
  const rows = [];
  let row = [], cell = '', inQuotes = false;
  // strip UTF-8 BOM
  const input = text.charCodeAt(0) === 0xFEFF ? text.slice(1) : text;

  for (let i = 0; i < input.length; i++) {
    const ch = input[i], next = input[i + 1];
    if (inQuotes) {
      if (ch === '"' && next === '"') { cell += '"'; i++; }
      else if (ch === '"') { inQuotes = false; }
      else { cell += ch; }
    } else {
      if (ch === '"') { inQuotes = true; }
      else if (ch === ',') { row.push(cell.trim()); cell = ''; }
      else if (ch === '\n') { row.push(cell.trim()); rows.push(row); row = []; cell = ''; }
      else if (ch === '\r') { /* skip */ }
      else { cell += ch; }
    }
  }
  if (cell || row.length) { row.push(cell.trim()); rows.push(row); }
  return rows;
}

function rowsToQuestions(rows) {
  return rows
    .map(row => ({ q: row[1]?.trim(), a: row[2]?.trim() }))
    .filter(({ q, a }) => q && a);
}

function toJSModule(data) {
  return `// Auto-generated by scripts/sync-qa.mjs — do not edit
// 最後同步：${new Date().toLocaleString('zh-TW', { timeZone: 'Asia/Taipei' })}

export const qaData = ${JSON.stringify(data, null, 2)};\n`;
}

async function main() {
  console.log('🔄 開始同步 QA 資料...\n');
  const qaData = [];

  for (const sheet of SHEETS) {
    process.stdout.write(`  ⬇️  ${sheet.label}... `);
    if (!sheet.url) {
      qaData.push({ category: sheet.label, questions: [PLACEHOLDER] });
      console.log('⏳ 尚未設定分頁 URL，使用佔位符（建立分頁後填入 gid）');
      continue;
    }
    const text = await fetchCSV(sheet.url);
    const questions = rowsToQuestions(parseCSV(text));
    qaData.push({
      category: sheet.label,
      questions: questions.length ? questions : [PLACEHOLDER],
    });
    console.log(questions.length ? `✅ ${questions.length} 題` : '空白，使用佔位符');
  }

  writeFileSync(OUTPUT_PATH, toJSModule(qaData), 'utf-8');
  const total = qaData.reduce((n, c) => n + c.questions.length, 0);
  console.log(`\n✅ 已寫入 ${OUTPUT_PATH}，共 ${qaData.length} 分類，${total} 題`);
}

main().catch((error) => {
  console.error('❌ QA 同步失敗:', error);
  process.exit(1);
});
