name: Push Commit to Deploy Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # 每週一早上 8:00 (台灣時間) 自動執行

jobs:
  push-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo at specific commit
        uses: actions/checkout@v4
        with:
          repository: 'lamb-liver/accusation-card-tool'
          ref: 'fdcfe12'
          fetch-depth: 0

      - name: Push to Destination Repository
        env:
          DEST_TOKEN: ${{ secrets.DEPLOY_REPO_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          REMOTE_URL="https://x-access-token:${DEST_TOKEN}@github.com/lamb-liver/accusation-card-tool.git"
          
          git push $REMOTE_URL HEAD:main --force
